[package]
name = "simon"
version = "0.1.0"
edition = "2021"

[dependencies]
sysinfo = "0.36.1"
tokio = { version = "1.46.1", features = ["rt", "macros", "sync"] }
axum = "0.8"
prometheus = "0.14"
tracing = "0.1.41"
tracing-subscriber = "0.3.19"
